### PR TITLE
Replace .. paths

### PR DESCRIPTION
**Pull request by merscwog**
Paths in gradle scripts should always be relative to current project, or an explicitly named project using the files() method of the Project class.

### CODE REVIEW

**Comment by rgatkinson** [comment]
Thanks for the suggestion. While I can see the logic in what you've done, reading between the lines I get the impression that you're seeing some apparent importance in the one style here vs the other that's not immediately obvious to me. Could you say a few words about why you prefer the style to which you changed things here?

**Comment by merscwog** [comment]
Right now, everything defined within build.common.gradle only works simply because it makes an assumption that all projects that might utilize it exist exactly one level below the root project level.
With the proposed changes, TeamCode could be moved into a :samples:TeamCode submodule, and it would still work just fine.
But, even more important, is that a submodule that lives in a directory outside of the ftc_app directory structure, but part of the logical multi-project build would work fine using the changed build.common.gradle.
ftc/  ftc_app/    FtcRobotController/
    TeamCode/
  Team519/  (same build/config files as TeamCode, but can be separate git repository easily)

There is an includeFlat() method that can be used within settings.gradle to include modules that are parallel to the root project directory (which in this case is ftc_app).
I have an additional prototype pull request waiting in the works that easily allows teams to house their code next to the ftc_app git project, and not have to deal with the nested git repository issue that exists now.  It currently simply looks for the pattern [Tt]eam([0-9])+ and includes all directories as subprojects that are found parallel to the ftc_app directory, and they can use the same (modified) build.gradle and other reference structure as TeamCode, but not have to live inside the ftc_app git repo directory structure.  The exact implementation is certainly up for discussion, but being able to easily decouple the team code repository from the ftc_app code git repository would be a huge win for everyone.

Having had to deal with refactoring large multi-project builds, I can say that the use of ".." in some places lead to lots of extra work trying to move things properly (which were changed).  Clearly in such a small project, it generally isn't a big deal, except that in this case using ".." limits leveraging how gradle allows subproject/submodules to be included as part of the larger build, which can be used to avoid a problem with how git repositories function, and also encourage most people to only make changes to files _outside_ of the ftc_app directory :-)

-Spencer

**Comment by cmacfarl** [comment]
Our team accomplishes the goal of an independent team repository by adding a sourceSets statement to the TeamCode gradle script along with a relative path back to the team repo that sits beside ftc_app in the directory structure.  It requires a single change to the TeamCode gradle that can be pushed up to a team fork of the ftc_app repo in a location that is specifically designed for custom changes.

So I'm with you on that as one of the first things I did last year was figure out how decouple team software from SDK software.

However, one of the problems I see with trying to scan for Team* directories is that most teams don't name their github repositories TeamXYZ.   Now, if your solution is being able to pick up anything that's in a subdirectory of TeamXYZ that might be useful.

**Comment by merscwog** [comment]
I had mentioned that one solution would be to automatically search for certain directory structure patterns and auto-include team projects, but there could also be a special ftc-team.gradle file that could contain a mapping of project team names to desired paths that would support single and multiple teams with any path structure.  Also, a combination of both ways, convention and configuration, could be implemented.  It would even be possible to have the existence of an external subproject cause the default TeamCode subproject to not be included at all, so there wouldn't be any temptation to alter code there.

There are several equally viable and potentially complementary solutions to keep team code outside of the ftc_app subdirectory, but all the ones that I currently can conceive that support shared multi-team builds and would leverage build.common.gradle yet not require any changes to the ftc_app repository by a team require named project referenced paths such as in this pull request.

I'd love to help implement a full-blown solution to keep single/multi-team code and project configuration options outside of the ftc_app repository directory.  I have more than enough gradle experience, but getting the customer requirements correct drives the constraints.  While my team is one consumer, it certainly would help to collate the normal usage and desired usage patterns of many teams :-)

**Comment by cmacfarl** [comment]
Hmm, I like the idea of a mechanism within the SDK which would automatically find TeamCodeLike modules that live outside of the root of the SDK with arbitrary naming.   However I think anything proposed should be exceedingly simple to use.  A configuration file that's parsed by gradle containing a mapping of some sort seems, at first blush, rather to not satisfy the exceedingly simple requirement.

What about a sentinel file that lives in an external module?  Your feature would scan all directories under the parent directory of the SDK looking for this sentinel.  If it finds it it either snarfs all the source in that subtree, or imports it as a module itself.

A general comment on pull requests for others that may be following this thread, the deployment model for the SDK does not allow for pulls directly into ftctechnh/ftc_app.   However that doesn't preclude you from forking ftctechnh/ftc_app, doing whatever you like in your fork, and then publicizing your fork in the official FTC forums and inviting other teams to use your fork instead of ftctechnh's.    If your changes are truly compelling to other teams, and violate no other game rules, people will migrate to your fork.  And if the changes are popular enough among the community, FIRST will hear of them and they may very well be incorporated into next year's SDK.   This is exactly what happened with SwerveRobotics last year.   The opmode annotations (indirectly by way of dmssargent), sounds, and synchronous controller operations all came that way.  The self inspector was ported in from a team that produced a standalone app. 

So I would encourage you to follow this path.   My team is already doing something similar without the automation.   So clearly there's a need among a certain set of teams.  Make something compelling enough and people will use it.

**Comment by cmacfarl** [comment]
This commit, https://github.com/ftctechnh/ftc_app/pull/216/commits/97fccf2cae57ab8ab0d0d058642f5a7d86dc15c8,  has been merged and will be in the next SDK release.

**Pull request closed without merging**
