### PR TITLE
Reviewing Progress Made Thus Far

### PR DESCRIPTION
**Pull request by ed-robotex**
I am actually playing with this pull request doohickey. Seeing how it works.

### CODE REVIEW

**Comment by magneticflux-** [comment]
As per #351:
>I really don't think you meant to ask FIRST to add your test class to the official repository. It's a common mistake for people who are new to Git and GitHub.
>You can delete this pull request.

**Comment by NoahAndrews** [comment]
@magneticflux- TODO comments are actually a standard thing. Android Studio will show you where you left all of them in the TODO pane. I like to use them to document little things that need improvement in the code, or notes to help me when I come back to working, and then I use GitHub issues for bugs, planned features, and such.

**Comment by magneticflux-** [comment]
@NoahAndrews While I totally agree with you that TODO comments inside of normal code is a good strategy to remind yourself what to do/what you were working on, they have an empty class file that only contains `// TODO` lines, which seems a little odd, to say the least. Especially since they could have simply made a text file instead of an empty class.

**Comment by NoahAndrews** [comment]
Eh, they said they were just figuring out how the feature works. For that, it makes enough sense to me.

**Pull request closed without merging**
