### PR TITLE
Test

### PR DESCRIPTION
**Pull request by CaptainFlareon**
Before issuing a pull request, please see the contributing page.

### CODE REVIEW

**Comment by NoahAndrews** [comment]
I really don't think you meant to ask FIRST to add your test class to the official repository. It's a common mistake for people who are new to Git and GitHub. 

You can delete this pull request.

**Comment by CaptainFlareon** [comment]
I'm really sorry about that. I'll delete the pull request as soon as I can.

We're experimenting with the GitHub desktop app; that's what we're new with
and where the problem came from.

Thanks for notifying me. It should help me figure out what's wrong. My
apologies again!

**Comment by magneticflux-** [comment]
@CaptainFlareon Quick tip, the GitHub desktop app probably isn't the best place to start. Learning to use Android Studio's build-in Git integration and learning some basic Git terminal commands is probably better in the long run.

**Comment by NoahAndrews** [comment]
@magneticflux- I would agree, except that neither of those options have a good way to commit only certain lines from a file. GitHub Desktop and Sourcetree both do that nicely, and JetBrains is working on adding that to IntelliJ, which will eventually make its way into Android Studio.

**Comment by magneticflux-** [comment]
@NoahAndrews I never knew that those clients could commit specific lines, thanks! I hope Android Studio Canary gets that feature soon so I don't have to mess with stashing as much.

**Comment by NoahAndrews** [comment]
I know, I can't wait. It'll be a while though. I'm hoping it will make it into IntelliJ 2017.3, and then maybe Android Studio 3.2 or 3.3. [You can get updates about it here.](https://youtrack.jetbrains.com/issue/IDEA-63201)

**Pull request closed without merging**
