### PR TITLE
Master

### PR DESCRIPTION
**Pull request by t42itoz**

### CODE REVIEW

**Comment by magneticflux-** [comment]
@t42itoz Please do not request team-specific code to be merged into the main FTC repository.

**Comment by t42itoz** [comment]
So sorry - still getting used to git. Did not mean to merge to the main branch. Not sure how to resolve this and get rid of this merge.

**Comment by magneticflux-** [comment]
@t42itoz That's fine! Just close the pull request.

**Comment by strugee** [comment]
@t42itoz you may want to check out [this GitHub article][1]; it may help you to understand how to do what you're trying to do.

 [1]: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by t42itoz** [comment]
Thank you so much for your help.

**Comment by t42itoz** [comment]
I wonder if you can help us - I accidentally created a branch of ftctechnh/master and would like to get rid of it. I am reading the manuals, but am leery of trying to merge or do anything with this ftctechnh/master branch without more expert advice. Any help would be much appreciated.

**Comment by strugee** [comment]
@t42itoz sure thing.

**Pull request closed without merging**
