### PR TITLE
Remove .iml files

### LINKED ISSUE #1: Default API version for compiling is set to 21
FtcRobotController/build.gradle instructs Gradle to try to build the app using Android SDK 21, which doesn't make sense given that it is designed for SDK 19 and SDK 22 is the newest release version.

### PR DESCRIPTION
**Pull request by JacobAMason**
FtcRobotController.iml and ftc_app.iml should not have been included in the repository and have been causing a bit of confusion with the whole API 19 vs API 21 thing.  These are project files which are generated at build-time and can cause JDK/SDK confusion when put on the computers of others.  Another side-effect of these files being included in the repo is that they are constantly trying to sneak themselves into your commits, which is a minor annoyance, but could be made better.

Users should be following the steps in FTCTraining Manual.pdf to determine how to configure their JDK and Android SDK.

Fixes #1

### CODE REVIEW

**Comment by NoahAndrews** [comment]
You're not really fixing the underlying issue here. What really should be done is to add a `*.iml` line to the `.gitignore` file

**Comment by JacobAMason** [comment]
@NoahAndrews I did this a while back in commit fb22997913aa1d668bc916e9bd112df2cb710c71, but adding an entry to a .gitignore doesn't remove a tracked file.

**Comment by NoahAndrews** [comment]
Yeah, I'm aware of that, I really meant that both should be done. 

So was that commit a pull request which actually got accepted (I'm not seeing any indication of that, but that could just mean a rebase), or are you affiliated with FIRST or Qualcomm somehow?

**Comment by JacobAMason** [comment]
@NoahAndrews, yes, PR #2 is merged by commit d39389f5953c65dbaf0f5f771c5134af29aff6c8
Here is the commit history: https://github.com/ftctechnh/ftc_app/commits/master

**Comment by NoahAndrews** [comment]
*facepalm* How did I miss that?

Anyway, it's great to see that they have accepted a pull request from the public before.

**Comment by JacobAMason** [comment]
@NoahAndrews ha, it's cool. Yes, I think they will accept a PR given that it is very focused. Of course, we've been told not to post issues here, which is somewhat confusing to me, but they didn't say we couldn't submit pull requests, so here's hoping that this will get accepted.

**Comment by markshancock** [comment]
I agree, the iml file made my merge with 160974c a pain.

**Comment by JacobAMason** [comment]
@ftctechnh @tomeng70 We had a short scrimmage over Halloween weekend and I the top issue I saw was teams getting stuck on the "Google API 19 SDK etc.. not found" when the SDK was indeed already on their systems.  This problem is because these .iml files are referencing the SDK by a different name.  Teams should be following the install guide, but the presence of these files is creating a misleading error.
I had somewhat anticipated this would be a problem but wasn't sure until actually seeing it "in the wild".  One team had downloaded 4 copies of the SDK (~25GB!) because this error was telling them the SDK wasn't present.

**Pull request closed without merging**
