### PR TITLE
Season production

### PR DESCRIPTION
**Pull request by derekred6**

### CODE REVIEW

**Comment by magneticflux-** [comment]
Please direct your attention to the other closed pull requests and learn more about how to use them.

**Comment by strugee** [comment]
As @magneticflux- mentioned, you're probably trying to [merge an upstream repository into your fork][1].

 [1]: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by magneticflux-** [comment]
@derekred6 Please close this pull request.

**Comment by magneticflux-** [comment]
@derekred6 If you would like assistance closing this pull request, feel free to ask.

**Pull request closed without merging**
