### PR TITLE
Updates from FTC Master + Teleop/Autonomous from 3 developers.

### PR DESCRIPTION
**Pull request by sugarcrystals01**
In Chronological Order:
Oct. 1 2017: Updates from FTC Master (ftc_technh/ftc_app)
Oct. 7 2017:
**Mrinaal**  (@mrinaalr): Autonomous Holonomic; Controlla.java, EagleEye.java, Terminator.java 
Commit Comment from Developer: "Intial Code."
**Samih** (@samihsq): testAutonomous.java, testTeleop.java; Edits to: Terminator.java, build.gradle
Commit Comment from Developer" "adding spin movement"
**Roma Bhatia**(@sugarcrystals01): Teleop Holonomic: HolonomicHardware.java, HolonomicTeleop.java
Commit Comment from Developer: "Holonomic Hardware Map & Teleop mode. Complete with rotations. Rotations untested, but works in theory."

### CODE REVIEW

**Comment by NoahAndrews** [comment]
I don't think you meant to attempt to merge your code into the main FTC repository

**Comment by sugarcrystals01** [comment]
Whoops, I don't think either!! Sorry about that!

**Comment by NoahAndrews** [comment]
Happens all the time, just press the close button

**Comment by sugarcrystals01** [comment]
Ok!

**Pull request closed without merging**
