### PR TITLE
Updating the lib for our fork

### PR DESCRIPTION
**Pull request by pranavburugula**
We're new to github. From what we understand, we need to create a request to update our fork. If this is the incorrect method, please send an email to us: pranav.burugula@gmail.com
Thanks
-FTC Team 9773

### CODE REVIEW

**Comment by cmacfarl** [comment]
If you've pulled a fork, not a clone, then you want to follow
these instructions.

  https://help.github.com/articles/syncing-a-fork/

Pull requests are for pushing changes back upstream which
is not what you want to do here.

Craig

**Comment by markshancock** [comment]
I am new to GIT as well.
First some terminology
A Fork would be a separate (private) external (GitHub) repository you forked off of another external repository.  All of this is online, has nothing to do with your local copy.
A Clone is a local copy of an external repository (such as ftctechnh/ftc_app or you own.
The whole 'Pull' thing is a bit confusing.  You create a 'Pull Request' to inform someone else that you have content that you would like them to Pull into their repository.

For example, I have my own GitHub repository markshancock/ftc_app that is forked from ftctechnh/ftc_app.  I then clone this to my local repository on my PC and commit and push changes to it as I make them on my PC as I develop.  When ftctechnh/ftc_app updates, I go to THEIR repository (not mine) and send a 'Pull Request' to my repository then go to my repository and accept the 'Pull Request' to incorporate their changes into my repository.  If I were instead to issue a 'Pull Request' from my GitHub account or to do a Push from my clone. It would be asking ftctechnh/ftc_app to incorporate my updates to their repository.

Does that make sense?  It took a while for me to grasp it.

**Comment by pranavburugula** [comment]
Thanks for clarifying! I guess it's a good thing I asked, because otherwise
I would've merged the repositories by accident, and that would be a big
headache for everyone!
Thanks again,
-FTC Team 9773

**Comment by ArchimedesPi** [comment]
@pranavburugula If you can close this pull request that would be great :)

**Pull request closed without merging**
