### PR TITLE
Update PushBotManual.java

### PR DESCRIPTION
**Pull request by CustomPCDotCom**

### CODE REVIEW

**Comment by magneticflux-** [comment]
@CustomPCDotCom What use does this have?

**Comment by strugee** [comment]
@CustomPCDotCom looks like this is a test - please don't send test PRs. Some of us get an email every time you do so.

**Comment by magneticflux-** [comment]
@CustomPCDotCom Please close this unnecessary pull request.

**Comment by CustomPCDotCom** [comment]
Sorry I'm new to this stuff and I will close the pull request

**Comment by xyzzycoder** [comment]
It might save time and improve the process to have some details on the main documentation page on Github to explain how to work with the team/source, how to contribute, when pull requests are appropriate, etc. 


Aaron

**Pull request closed without merging**
