### PR TITLE
Erics branch

### PR DESCRIPTION
**Pull request by jovanus**

### CODE REVIEW

**Comment by jovanus** [comment]
Good!

**Comment by strugee** [comment]
@jovanus are you intending for these changes to be merged back into the FTC repo? If so, you probably shouldn't have deleted all their examples. If not, you probably shouldn't have sent this Pull Request.

**Comment by jovanus** [comment]
It was a mistake. Just trying to fix my code, sorry will close.

**Comment by strugee** [comment]
@jovanus I've seen a lot of teams trying to merge changes in the FTC SDK to their repo via Pull Requests. Was this what you were trying to do? If so, you don't need to use Pull Requests. Check out [this GitHub Help article][1] for how to do this.

 [1]: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Pull request closed without merging**
