### PR TITLE
Allow asymmetric driving with encoderDrive.

### PR DESCRIPTION
**Pull request by FireClaw**
Asymmetric driving (such as point turns) causes one motor to finish and the entire function to stop.
Fixed by replacing an and operator with an or.

Dacio Romero 
Highschool mentor for FTC teams 11617, 11618, and 11729
Programmer for FRC team 1502

EDIT: Changed "swing turns" to "point turns" for clarity.

### CODE REVIEW

**Comment by gearsincorg** [comment]
Thanks for your input.  It's good to see that you are extending the samples to do more driving.

However, in the given example, the choice to use && (and) rather than || (or) was a conscious one.

In the majority of driving cases (everything except a single wheel turn), it's desirable to stop both motors at the same time at the end of the run.  If this isn't done, then you get a noticeable "jerk" at the end of the motion.  

By using && we guarantee that both motors stop at the same time.

This logic can be extended for sweeping turns, assuming that you adjust BOTH the speed and encoder counts for both wheels.  The premise that both motors should stop at the same time is upheld in this case.

In the case of single wheel pivot turns, only one motor is being driven, so the code should be adapted to only run, and check that single wheel.

That being said, using || (or) is equally valid if you want to ensure both wheels move the total prescribed distance, regardless of the jerk.  This just wasn't the primary design factor in this set of examples.

Phil.

**Comment by olekmali** [comment]
We (Team #9985) discovered that "feature" one week ago and corrected it 
both for encoderDrive and gyroDrive examples. So far in testing we did 
not discover any problems with driving forward for a specified distance.

Unless you can demonstrate the negative effects I would advise to 
incorporate the fix.

Kind regards,

Dr. Aleksander 'Olek' Malinowski
phone: +1 (309) 306 1131
skype: olekmali
http://www.bradley.edu/academic/departments/electrical/faculty/profile.dot?id=10917dd0-3092-4e27-95f5-7eb07a52e1c5

**Comment by FireClaw** [comment]
Any conclusions on whether or not to merge this?

**Comment by cmacfarl** [comment]
To the extent that this is example software, I think that deference to the
original author is appropriate.  To which I agree with Phil.

A more appropriate pull request might be a comment, perhaps rather
comprehensive, that attempts to explain why allowing the motor that is
lagging the encoder count to dictate when both motors stop might be
desirable in some circumstances.  And then explain that this is not the
behavior here.

After all, the overriding goal of FIRST is education.   The examples were
to help in that regard.   Comments explaining what's going on and why that
might not be ideal for some situations are certainly welcome in the cause
of furthering that mission.

**Comment by gearsincorg** [comment]
>  explain why allowing the motor that is lagging the encoder count to dictate when both motors stop might be desirable in some circumstances.

Yes, describing both approaches (pros/cons) would be a good addition.  (then let the user choose to change it if desired).  I will work on adding some additional explanations to those examples.

Thanks for suggesting that.

**Comment by qwertychouskie** [comment]
> To elaborate further.. requiring a simultaneous !isBusy() has other negative ramifications. Since opposing drive wheels often cause the robot to "hunt" in it's final position, it's not always the case that both drives go !isBusy() at the same time. They can alternate in and out of the final !isBusy() condition for a long period. The robot appears to get "Stuck" between motions.

This PR changes it to NOT require a simultaneous !isBusy(), it changes it from

    robot.leftMotor.isBusy() && robot.rightMotor.isBusy()

to

    robot.leftMotor.isBusy() || robot.rightMotor.isBusy()

**Comment by qwertychouskie** [comment]
And I can testify from personal experience x.isBusy() **&&** y.isBusy() is **VERY DANGEROUS FOR COMPETITION USE**.  Even using isBusy() on only one motor can lose you a match: https://www.youtube.com/watch?v=eueYRNEkSiU (we're the robot on the far left).  Although this has a timeout (which we soon added to our code :) ), you are pretty much only relying on the timeout in this case, meaning you are loosing valuable time.

**Comment by JacobAMason** [comment]
> Yes, describing both approaches (pros/cons) would be a good addition. (then let the user choose to change it if desired). I will work on adding some additional explanations to those examples.
@gearsincorg Phil, unless you still want to add a comment to clarify the example, it's probably fine to close this.

**Comment by gearsincorg** [comment]
An additional comment indicating the alternative termination option has been added to the current sample.

**Pull request closed without merging**
