### PR TITLE
Allow more flexible team code directories rather than 'TeamCode'

### PR DESCRIPTION
**Pull request by jeremycole**
Hello FTCers!

This pull request modifies 'settings.gradle' to include all directories marked with a '.teamcode' sentinel file, rather than just the 'TeamCode' directory. This can allow a team to maintain a fully independent git repository consisting of just their team code sub-directory, which can easily be checked out into their local 'ftc_app' directory (regardless of the source) without any file/directory conflicts or manual mangling of directory contents.

This also allows multiple team code directories to co-exist peacefully, so that a team with multiple robots can more easily use the same Android Studio and same ftc_app repository to work with both robots (or OpMode subsets for the same robot) by changing only the configuration dropdown to choose one. (Currently it's possible to do this by editing 'settings.gradle' to add your custom directories, but even this becomes no longer necessary.)

Notes:
  1. I am by *far* not an expert in Gradle (or even Java or Android). I hacked my way through this, so if the code looks stupid or does something it shouldn't, feel free to change it as necessary.
  2. I used the presence of a '.teamcode' file to mark that a directory should be included mainly to ensure it doesn't go on a rampage of including directories it shouldn't – however if there's a better way, or it seems unnecessary, or even if it should have a different name, it's also fine to change that!
  3. This works for me locally, and it seems generally useful. So I thought I'd send in a PR and see what you guys think!

Regards,

Jeremy

### CODE REVIEW

**Comment by asowder3943** [comment]
I would like to see this added

**Comment by magneticflux-** [comment]
I'm not that familiar with Groovy, but could you possibly refactor that loop into a set of filters on the files? I think it would make the algorithm easier to understand. I'm thinking something like this:
```Gradle
teamFiles
    .filter { it.isDirectory() }
    .filter { file(it.name + '/.teamcode').exists() }
    .each {
        include ':' + teamDirectory.name
        teamDirectoryFound = true
    }
```

You could also add a condition like `it.name.endsWith('TeamCode')` to pickup the TeamCode directory without having to resort to an external boolean state, which would also have the side-effect of not allowing marked subprojects as well as an unmarked TeamCode subproject.

You also should consider switching from the `java.io.File` APIs to the newer `java.nio.file.Path` APIs, which are [much better](https://stackoverflow.com/a/26658436).

Sorry for all the bikeshedding!

**Comment by cmacfarl** [comment]
As mentioned elsewhere, the release process does not, as a general rule, allow direct commits to ftc_app.   Thank you for demonstrating how to do this.  Other teams are free use this diff as a resource.  The FTC Technology Team will evaluate whether or not the existing TeamCode mechanism is insufficient.

**Comment by jeremycole** [comment]
Given I submitted this as a pull request you're free to do with it whatever you like, but FWIW, I have no idea what this means:

> As mentioned elsewhere, the release process does not, as a general rule, allow direct commits to ftc_app.

Also FWIW, we used this all last season and are continuing with it this year, and it works great, allowing us to have `TeamCode_2016`, `TeamCode_2017`, and `TeamCode_2018` directories that exist in separate Git repositories containing only TeamCode (cloning `ftc_app` and `TeamCode_xyz` separately). Managing our team's code has never been simpler, and we'll keep doing that with our fork.

It makes me sad that I can't easily suggest the same TeamCode source management strategy that we so happily use for all of the teams that I mentor without undue burden just because this simple non-breaking change is floating in the ether. 🤷‍♂️

**Comment by cmacfarl** [comment]
It means that the process to build and deploy software to ftc_app involves an internal repository where all the "master" software is managed and from which development flows.  If something gets changed in ftc_app, without a corresponding change to its analog in the internal repository, then deployment of the next revision could break.    As a general rule, this undesirable, prone to error, etc, and hence we don't do direct commits to ftc_app.

I am also a mentor of two teams, and we also store all our team software in team specific git/github repositories.  We use gradle's sourceSets feature to snarf in the external software.  Works great, and allows for easy team code management, decoupled completely from the ftc_app directory structure.  We never nest team software in ftc_app.  It's worked for us for the last 3 years.  We just maintain a fork of ftc_app and team specific branches off of ftc_app:master that contain a few simple lines of gradle for each team.

I encourage you to publicize your fork on reddit, discord, the forums, etc.  If teams find it useful, they can easily pick it up and use it.  In the meantime, we'll have some internal discussions about team software management.  Thank you.

**Pull request closed without merging**
