### PR TITLE
Merge remote-tracking branch 'ftctechnh/master'

### PR DESCRIPTION
**Pull request by jjkd**

### CODE REVIEW

**Comment by mhaeberli** [comment]
jjkd - can you please provide a description for your pull request?

**Comment by jjkd** [comment]
Hi Martin, sorry, please reject/ignore this, my mistake - I clicked the
wrong thing and are still getting used to GIT...

**Comment by strugee** [comment]
@jjkd in that case, you should close the Pull Request by clicking "close" at the bottom of the web page.

Also, you don't need to involve Pull Requests (or GitHub at all) in order to perform merges. You can do it all locally with the `git` command.

**Comment by jjkd** [comment]
Closing incorrect pull request, thanks for the feedback!

**Pull request closed without merging**
