### PR TITLE
Clean up duplicate release info header and properly format code

### PR DESCRIPTION
**Pull request by richiksc**
Yes, I understand Git and GitHub and meant to open this pull request.

### CODE REVIEW

**Comment by richiksc** [comment]
@qwertychouskie @magneticflux- how many people have to approve it to get it merged? Who has the final say?

**Comment by magneticflux-** [comment]
@ftctechnh Has the final say, we're just plebians lol

**Comment by richiksc** [comment]
@ftctechnh any comments?

**Comment by cmacfarl** [comment]
The release process, as a general rule, does not allow for direct commits to ftc_app.  If there are grammatical and/or changes you'd like to see you may open an issue describing them and the request will be evaluated.  Thank you.

**Pull request closed without merging**
