### PR TITLE
Camera test

### PR DESCRIPTION
**Pull request by jrasor**
Tiny edit.

### CODE REVIEW

**Comment by magneticflux-** [comment]
As per #351:
>I really don't think you meant to ask FIRST to add your test class to the official repository. It's a common mistake for people who are new to Git and GitHub.
>You can delete this pull request.

In your case, I think you were trying to make a pull request for *your* `master` branch from your `testing` branch, but accidentally chose the wrong base.

**Comment by jrasor** [comment]
Hi, Mitchell!

**Comment by jrasor** [comment]
@Mitchell: Aaargghh! How does one delete a pull request?

**Comment by cmcknight** [comment]
Visit the pull request page
Tap the "close pull request button"

**Comment by magneticflux-** [comment]
@jrasor Sorry, but Pull Requests are around forever. The proper way to "get rid" of one is to close it.

**Comment by jrasor** [comment]
@magneticflux and @cmcknight : thanks, doing that...

**Pull request closed without merging**
