### PR TITLE
Remove unused dependency android-support-v4.jar

### PR DESCRIPTION
**Pull request by aj-foster**
It appears this library is unused, and furthermore it is not included in the repository.

@tomeng70, please feel free to tell me if you do or don't want pull requests like this. If pulling to another branch is easier, or anything like that, just let me know.

### CODE REVIEW

**Comment by aj-foster** [comment]
Closing, as I understand public contributions are not part of the plan.

**Comment by lukethecoder64** [comment]
What plan? Iirc FTC has communicated no opinions on PRs.

On Monday, June 6, 2016, AJ Foster <notifications@github.com> wrote:

> Closing, as I understand public contributions are not part of the plan.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ftctechnh/ftc_app/pull/172#issuecomment-224042142>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJD87eOIfhR2AIlfInXeuRWalOgUOHF3ks5qJGPWgaJpZM4IuSW7>
> .
>


-- 
Luke
     __
    /   /
   /   /
  /   /
 /   /______
/_________/

**Comment by magneticflux-** [comment]
@lukethecoder64 It is abundantly clear that FTC was not prepared to release the app code on Github, but did it anyway, for better or worse. Contributions to code are not being considered at this time, judging from similar pull requests.

**Comment by aj-foster** [comment]
To be fair, the development team deals with a lot of moving parts which can't be seen by us. It makes sense for them to develop elsewhere and put the results here, for now. There are [discussions](http://ftcforum.usfirst.org/showthread.php?6732-FTC-Technology-Forum-at-2016-FIRST-Championship&p=27611&viewfull=1#post27611) about bringing more of it into the open, but FIRST has a lot to consider before that can be decided.

In the meantime, sharing information about issues and their fixes with FIRST (through GitHub issues) and other teams (through blog posts and forks) can't hurt.

**Pull request closed without merging**
