### PR TITLE
Sbd9871 firstbranch

### PR DESCRIPTION
**Pull request by sheilgrandhi**

### CODE REVIEW

**Comment by smo-key** [comment]
Hi @sheilgrandhi! Can you please add a description of your changes? It appears to me that most of the code you added is team- or robot-specific and might not be suitable for merge.

**Comment by team3733** [comment]
does anyone now were we can get the android programing at?

**Comment by aravindkoneru** [comment]
@team3733 I'd recommend reading through the documentation provided by FIRST that's in this repo. Here's the [official FIRST documentation](https://github.com/ftctechnh/ftc_app/tree/master/doc/tutorial) that has information on how to set up the Android Environment.

**Comment by team3733** [comment]
i looked throught all of that and it didnt seem to help ill get some today

**Comment by keeneyes** [comment]
Go to: first.intelitek.com

Free to use, just sign up. Very detailed tutorials on how to get everything going.

**Comment by aravindkoneru** [comment]
I taught a Java class to the team I mentor a few weeks ago. Here's the [repository](https://github.com/aravindkoneru/JavaClass) if it'll be of any help. I have the instructions on how to install everything under lessons and some basic information about java as well.

**Comment by JacobAMason** [comment]
Not sure what this is, but it looks like someone accidentally issuing PRs without quite knowing how this works.  Probably should close this one.

**Pull request closed without merging**
