### PR TITLE
Merging updates from the base repo.

### PR DESCRIPTION
**Pull request by Sass-Meister**

### CODE REVIEW

**Comment by KingofGamesYami** [comment]
I think you meant to pull from the ftctechnh:master repo to your own.  The URL for doing that is formatted as follows:

`https://github.com/<Your Name>/ftc_app/compare/master...ftctechnh:master`

**Comment by Sass-Meister** [comment]
Thanks a bunch, still getting used to all this stuff.

**Comment by strugee** [comment]
See also https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by cmacfarl** [comment]
And/or

https://help.github.com/articles/syncing-a-fork/

**Pull request closed without merging**
