### PR TITLE
Add "How to Use Git" to README to stem the tide of pull requests

### PR DESCRIPTION
**Pull request by cchan**
Though teams have clearly been able to get this information elsewhere, it might be helpful for those starting out with Git to have this info conveniently right here.

### CODE REVIEW

**Comment by cchan** [comment]
I'd love to add http://rogerdudler.github.io/git-guide/ but who knows if it's possible with legal issues and all.

**Comment by lukethecoder64** [comment]
+1. Good luck getting the pull accepted, though.

You have my sword.

**Comment by strugee** [comment]
@cchan certainly you can link to it, but you can't include any of the actual text until rogerdudler/git-guide#58 is fixed.

**Comment by strugee** [comment]
I also [wrote a presentation][1] - feel free to link to it. Your choice

 [1]: http://saasrobotics.com/presentation-git-your-ftc-on/

**Comment by cchan** [comment]
Yay, thanks for the support. @strugee your presentation link is broken :/

**Comment by strugee** [comment]
@cchan works from here, [and from the internet][1]. Check your DNS settings, maybe?

 [1]: http://isup.me/saasrobotics.com

**Comment by cchan** [comment]
Works now! It was serving me an Nginx installation-success page for some reason.

**Comment by strugee** [comment]
> Works now! It was serving me an Nginx installation-success page for some reason.

Ah, thought you meant the server was completely unreachable. Sounds like a transient GitHub Pages issue.

**Comment by PranavMathur** [comment]
Since the git-guide repository is published on GitHub, it is technically open source. It does not have a license, so [this site](http://choosealicense.com/no-license/) describes the legal standpoint of using the page. @RogerDudler should be asked in any case, as it is his work.

**Comment by strugee** [comment]
@PranavMathur actually, it is neither open source nor free software. According to [the Open Source Definition][1], you need the right to freely redistribute software. You cannot do this with git-guide. GitHub's terms of service say that you must allow your repository to be forked but says nothing about redistribution. Hence, it's not open source. It's not [free software][2], either, since it (again) violates freedom 2 and freedom 3.

 [1]: https://opensource.org/osd-annotated
 [2]: https://www.gnu.org/philosophy/free-sw.en.html

**Comment by magneticflux-** [comment]
@strugee Linking to the site is _definitely_ not redistribution. If FIRST were to copy the "git-guide" text in its entirety and paste it into their own wiki, then copyright law would come into play. See https://en.wikipedia.org/wiki/Copyright_aspects_of_hyperlinking_and_framing

**Comment by lukethecoder64** [comment]
Back to the OP: I see no reason for FTC to deny this pull. Anybody know of a way to push for this getting accepted?

**Comment by strugee** [comment]
@magneticflux- I thought we were talking about copying the text. Linking is clearly not redistribution and so isn't a problem.

**Comment by cchan** [comment]
Bump. Does anyone from FTC read these? If not, please explicitly state that somewhere.

**Comment by lukethecoder64** [comment]
Why was this closed? From my understanding, OP still wants this accepted.

**Comment by magneticflux-** [comment]
@lukethecoder64 , @ftctechnh went on a closing spree and closed about 8 various pull requests, mostly spam.

**Comment by MeRPG** [comment]
@magneticflux- , but this PR wasn't spam. It really should be accepted.

**Comment by magneticflux-** [comment]
@MeRPG I wasn't saying it was, I was only trying to establish context for the close. It seems like a blanket close, since there were many more spam PRs than not.

**Comment by ftc5720** [comment]
@lukethecoder64 and @ftctechnh really need to learn the Github system. While many of these pr's are spam from teams learning the github system, some of them very useful additions to their buggy and overall shitty code.  Fuck FTC for blindly closing all of these. It's as though when they decided to make this public repo they simply didn't want to pay for a private one. The system would be better if they had left it closed source and simply had a downloadable runner, using something like the dynamic jar system @ZachOhara implemented in pull request #18 . Fuck FTC for not learning the very basics of collaborative programming and the use of github. None of this change was prepared for and all of their code was put together by what seems to be a Freshman English major. Some of these requests are powerful additions to the ftc_app, but if FTC refuses to listen, it will only die. FTC used to be great; now it is only an ant hiding in the shadow of FRC. Even FLL has their shit together more than this fucking awful system. FTC needs to step up its game and become what it once was.

Make FTC great again.

**Comment by rgatkinson** [comment]
Regarding this pull, #145, and specifically the set of instructions that were proposed for addition: I think reasonable people can differ on whether these instructions were the appropriate choice for inclusion or not. While I have every reason to believe that they were *correct* so far as they went, it is, for example, far from everyone that is using the command line to work with git, especially relative beginners, for whom this kind of instruction is most important. 

I do heartily agree that significantly better guidance, documentation, tutorials, etc would be useful and welcome regarding git (and other matters); I'm just saying that (rudely) objecting that this particular pull was not honored to achieve that end seems to me to be a little harsh.

**Comment by lukethecoder64** [comment]
@ftc5720 , may I ask when I demonstrated that I did not have a reasonable understanding of the Github (and git, there is a big difference) system?

**Pull request closed without merging**
