### PR TITLE
FTC Beta Test

### PR DESCRIPTION
**Pull request by wxtrav**

### CODE REVIEW

**Comment by strugee** [comment]
Are you perhaps trying to [merge an upstream repository into your fork][1]?

 [1]: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by wxtrav** [comment]
Forgive my ineptness with github.  Trying to copy the beta into a private
repository, and create instructions for our team programmers to manage the
code in their own branch of the repository. I guess I need to read more
docs.

Thanks,

Travis

**Comment by strugee** [comment]
@wxtrav if you clone an empty repository, you can change into the repo's directory and run `git pull https://github.com/ftctechnh/ftc_app.git master` and then push.

**Comment by strugee** [comment]
At least, I think. If that doesn't work you'll have to add a new remote.

**Comment by wxtrav** [comment]
I was able to fork it to a repo on github.  That should let the kids check
in their work from a couple of different computers on the fork, and still
allow it to sync with any changes on the master.  At least that's the way I
understand it to work (and we have one repo set up that way already).

I think i just got confused by "pull", which to me means "I pull the code
from the repo" when it seems to mean the opposite!

Thanks for your help!

**Comment by strugee** [comment]
"Pull" means that you download commits from a remote repository like this repository or your fork, both on GitHub, into your local copy. "Push" means that you push some commits that you have on the local computer up to a remote repository, like (again) a copy on GitHub.

**Comment by magneticflux-** [comment]
Actually, you're requesting for the main repository to "pull" commits from your fork. Not requesting to pull commits from the main repository to your fork. Git likes to switch things around; it can be tricky to learn how each function works.

**Comment by strugee** [comment]
@magneticflux- I was explaining what `git pull` does, not what a Pull Request is. Although I see now that I didn't actually specify that.

**Pull request closed without merging**
