### PR TITLE
Memes

### PR DESCRIPTION
**Pull request by htlee1500**
Halp

### CODE REVIEW

**Comment by magneticflux-** [comment]
@htlee1500 @Dmallery @sameer-s 
What a quality PR; this is what I live for.

On a more serious note, as per #351:
>I really don't think you meant to ask FIRST to add your test class to the official repository. It's a common mistake for people who are new to Git and GitHub.
>You can delete this pull request.

**Comment by sameer-s** [comment]
Sorry, it seems that someone on our team (cough cough) didn't fully get how Git works.

I'll delete it.

**Comment by cmacfarl** [comment]
Let's all try to remember that Gracious Professionalism is a foundation of the program.

Let's also acknowledge that learning Git happens.  And it happens here.  And that's fine.  This is a safe space.  Thanks all!

**Comment by sameer-s** [comment]
Oh, I didn't mean for it to come across like that, although I do admit that my choice of wording was pretty bad. I'm sure that everything will work out alright. Thanks!

**Comment by cmacfarl** [comment]
@sameer-s I was specifically referring to the sarcasm in @magneticflux-'s response.    Which was likely meant to be humorous, but which could come across a tad sharp to the recipient.  Just a gracious reminder to be gracious.

**Comment by qwertychouskie** [comment]
@htlee1500 @sameer-s @Dmallery

P.S. If you want memes, check out https://www.youtube.com/channel/UCpSItH8a8vWw5IcwylQ21Xg

P.P.S. Might be a bit biased ;)

**Pull request closed without merging**
