### PR TITLE
Sync the latest

### PR DESCRIPTION
**Pull request by zgg1220**
Before issuing a pull request, please see the contributing page.
Sync the latest version from ftctechnh/ftc_app

### CODE REVIEW

**Comment by qwertychouskie** [comment]
@zgg1220 As per #351:

> I really don't think you meant to ask FIRST to add your test class to the official repository. It's a common mistake for people who are new to Git and GitHub.
> You can delete this pull request.

**Comment by zgg1220** [comment]
@qwertychouskie I thought Pull means from the parent to the forked branch. My mistake. When you say "delete this pull request", do you mean I just close this request?

**Comment by cmacfarl** [comment]
Pull means, "To a local repository from a remote repository".  So you can
pull changes from a parent into your fork, or you can _request_ that the
maintainer of the parent pull changes from your fork into the parent.  In a
pull request the local and remote are reversed from your perspective since
the pull is from the perspective of the remote.  Push means, "To a
repository from a remote."   And of course you need to have permission, or
be a maintainer, of the remote.

**Comment by cmcknight** [comment]
There is a great resource for Git at git-scm.org, the Pro Git book, that covers git in great gory detail that I have my kids working through. It gives good explanations for the terminology, setting up repositories, and using for.

**Pull request closed without merging**
